import { knowledgeBase } from "./knowledge.js";
import { evaluateRisk } from "./policies.js";

export const toolCatalog = [
  {
    name: "search_knowledge",
    permission: "read",
    description: "Search local agent engineering knowledge snippets."
  },
  {
    name: "risk_check",
    permission: "read",
    description: "Check whether a task or action needs human review."
  },
  {
    name: "draft_execution_plan",
    permission: "write-dry-run",
    description: "Draft a structured implementation plan without changing external systems."
  },
  {
    name: "create_ticket",
    permission: "write-dry-run",
    description: "Create a dry-run ticket object for handoff."
  }
];

export async function runTool(name, input, context) {
  if (!toolCatalog.some((tool) => tool.name === name)) {
    throw new Error(`Unknown tool: ${name}`);
  }

  if (name === "search_knowledge") {
    const query = String(input.query || "").toLowerCase();
    return knowledgeBase
      .map((doc) => ({
        ...doc,
        score: scoreDoc(doc, query)
      }))
      .filter((doc) => doc.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);
  }

  if (name === "risk_check") {
    return evaluateRisk(input.task || context.task, input.action);
  }

  if (name === "draft_execution_plan") {
    return {
      objective: context.task,
      steps: [
        "Confirm success criteria and constraints.",
        "Use read-only tools to gather relevant context.",
        "Identify risks and required approvals.",
        "Produce a dry-run implementation or handoff plan.",
        "Validate the output against the original task."
      ],
      stopCondition: "All success criteria are addressed or a blocked risk is found."
    };
  }

  if (name === "create_ticket") {
    return {
      mode: context.mode,
      title: input.title || `Agent handoff: ${context.task.slice(0, 72)}`,
      body: input.body || "Dry-run ticket generated by Agent Lab Console.",
      externalWritePerformed: false
    };
  }
}

function scoreDoc(doc, query) {
  if (!query) return 0;
  const haystack = `${doc.title} ${doc.tags.join(" ")} ${doc.content}`.toLowerCase();
  return query
    .split(/\W+/)
    .filter(Boolean)
    .reduce((score, token) => score + (haystack.includes(token) ? 1 : 0), 0);
}
